language: bash
services: docker

env:
  - VERSION=3.2

install:
  - git clone https://github.com/HBKEngineering/mongodb-plus-mms-docker.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="mongo:$VERSION"

script:
  - docker build -t "$image" .

after_script:
  - docker images

# vim:set et ts=2 sw=2:
